# Generated by Django 5.2.17 on 2026-08-28 15:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("pretix", "Pretix"), ("native", "Werkblatt")], max_length=16
                    ),
                ),
                ("external_reference", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=300)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workshops",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_reference", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=200)),
                ("imported_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="workshops.workshop",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="workshop",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_reference", ""), _negated=True),
                fields=("organization", "source_type", "external_reference"),
                name="workshop_unique_external_reference_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="workshopregistration",
            constraint=models.UniqueConstraint(
                fields=("organization", "workshop", "external_reference"),
                name="registration_unique_external_reference",
            ),
        ),
    ]
