# Generated by Django 5.2.17 on 2026-09-05 09:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_organization_address_organization_email_and_more"),
        ("workshops", "0002_workshopregistration_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="documentation_requirement",
            field=models.CharField(
                choices=[
                    ("required", "Dokumentation erforderlich"),
                    ("not_required", "Keine Dokumentation erforderlich"),
                ],
                default="required",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="parent_external_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="workshop",
            name="requirement_decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workshop",
            name="requirement_decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workshop_requirement_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="requirement_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="workshop",
            name="requirement_source",
            field=models.CharField(
                choices=[
                    ("default", "Standard"),
                    ("event_rule", "Pretix-Veranstaltungsregel"),
                    ("individual", "Einzelentscheidung"),
                ],
                default="default",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="visibility",
            field=models.CharField(
                choices=[("active", "Sichtbar"), ("hidden", "Ausgeblendet")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="visibility_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workshop",
            name="visibility_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workshop_visibility_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PretixEventRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_slug", models.CharField(max_length=255)),
                ("display_name", models.CharField(blank=True, max_length=300)),
                ("import_enabled", models.BooleanField(default=True)),
                (
                    "documentation_requirement",
                    models.CharField(
                        choices=[
                            ("required", "Dokumentation erforderlich"),
                            ("not_required", "Keine Dokumentation erforderlich"),
                        ],
                        default="required",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pretix_event_rule_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pretix_event_rules",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name", "event_slug"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "event_slug"),
                        name="pretix_event_rule_unique_slug_per_organization",
                    )
                ],
            },
        ),
    ]
