# Generated by Django 5.2.17 on 2026-09-25 09:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_organization_address_organization_email_and_more"),
        ("workshops", "0004_workshop_lifecycle_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PretixEventCreationPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("template_event_slug", models.CharField(max_length=255)),
                ("primary_item_internal_name", models.CharField(max_length=200)),
                ("child_item_internal_name", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pretix_event_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pretix_creation_presets",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_pretix_event_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="PretixFundingText",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("text", models.TextField(max_length=5000)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pretix_funding_texts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pretix_funding_texts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_pretix_funding_texts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="PretixEventCreation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, max_length=10000)),
                ("funding_text_snapshot", models.TextField(blank=True, max_length=5000)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("capacity", models.PositiveIntegerField()),
                ("child_registration_enabled", models.BooleanField(default=False)),
                ("external_slug", models.CharField(max_length=255)),
                ("external_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("creating", "Wird erstellt"),
                            ("created", "Erstellt"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("template_invalid", "Vorlage ungültig"),
                            ("slug_conflict", "Slug bereits vergeben"),
                            ("pretix_unavailable", "Pretix nicht erreichbar"),
                            ("pretix_rejected", "Pretix hat die Anfrage abgewiesen"),
                            ("verification_failed", "Ergebnisprüfung fehlgeschlagen"),
                        ],
                        max_length=80,
                    ),
                ),
                ("preset_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pretix_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pretix_event_creations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_creations",
                        to="workshops.pretixeventcreationpreset",
                    ),
                ),
                (
                    "funding_text",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_creations",
                        to="workshops.pretixfundingtext",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="pretixeventcreationpreset",
            constraint=models.UniqueConstraint(
                fields=("organization", "display_name"),
                name="pretix_creation_preset_unique_name_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="pretixeventcreationpreset",
            constraint=models.UniqueConstraint(
                fields=("organization", "template_event_slug"),
                name="pretix_creation_preset_unique_template_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="pretixeventcreationpreset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("primary_item_internal_name", models.F("child_item_internal_name")),
                    _negated=True,
                ),
                name="pretix_creation_preset_distinct_items",
            ),
        ),
        migrations.AddConstraint(
            model_name="pretixfundingtext",
            constraint=models.UniqueConstraint(
                fields=("organization", "display_name"),
                name="pretix_funding_text_unique_name_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="pretixeventcreation",
            constraint=models.UniqueConstraint(
                fields=("organization", "external_slug"),
                name="pretix_event_creation_unique_slug_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="pretixeventcreation",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gte", 1)),
                name="pretix_event_creation_positive_capacity",
            ),
        ),
    ]
