# Generated by Django 5.2.17 on 2026-09-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0005_pretix_event_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
