# Generated by Django 5.2.17 on 2026-09-29 09:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_organization_address_organization_email_and_more"),
        ("workshops", "0006_workshop_capacity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pretixeventcreation",
            name="registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OpenWorkshopSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("schedule_description", models.CharField(blank=True, max_length=300)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_workshop_series",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OpenWorkshopAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("occurred_on", models.DateField()),
                ("total", models.PositiveIntegerField()),
                ("female", models.PositiveIntegerField(default=0)),
                ("male", models.PositiveIntegerField(default=0)),
                ("diverse", models.PositiveIntegerField(default=0)),
                ("unspecified", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_workshop_attendances",
                        to="organizations.organization",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_open_workshop_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendances",
                        to="workshops.openworkshopseries",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "series__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="openworkshopseries",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="open_workshop_series_unique_name_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="openworkshopattendance",
            constraint=models.UniqueConstraint(
                fields=("organization", "series", "occurred_on"),
                name="open_workshop_attendance_unique_date",
            ),
        ),
    ]
