# Generated by Django 5.2.17 on 2026-08-28 18:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import werkblatt.documents.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documentation", "0002_documenttemplate_documenttemplateversion_and_more"),
        ("organizations", "0002_organization_address_organization_email_and_more"),
        ("workshops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("output_kind", models.CharField(max_length=32)),
                ("output_name", models.CharField(max_length=200)),
                ("input_sha256", models.CharField(max_length=64)),
                ("renderer_version", models.CharField(default="weasyprint-66/v1", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("rendered", "Erzeugt"),
                            ("stored", "Extern gespeichert"),
                            ("render_failed", "PDF-Erzeugung fehlgeschlagen"),
                            ("storage_failed", "Externe Speicherung fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        upload_to=werkblatt.documents.models.generated_document_path,
                    ),
                ),
                ("pdf_sha256", models.CharField(blank=True, max_length=64)),
                ("byte_size", models.PositiveIntegerField(default=0)),
                ("storage_key", models.CharField(blank=True, max_length=500)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error_class", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_documents",
                        to="documentation.documentationrevision",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documentation.documenttemplateversion",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_documents",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "organization",
                            "workshop",
                            "revision",
                            "template_version",
                            "output_kind",
                            "input_sha256",
                        ),
                        name="generated_document_idempotent_output",
                    )
                ],
            },
        ),
    ]
