# Generated by Django 5.2.17 on 2026-08-28 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentation", "0002_documenttemplate_documenttemplateversion_and_more"),
        ("documents", "0001_initial"),
        ("organizations", "0002_organization_address_organization_email_and_more"),
        ("workshops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="generateddocument",
            name="generated_document_idempotent_output",
        ),
        migrations.AddConstraint(
            model_name="generateddocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revision__isnull", False)),
                fields=(
                    "organization",
                    "workshop",
                    "revision",
                    "template_version",
                    "output_kind",
                    "input_sha256",
                ),
                name="generated_document_idempotent_output",
            ),
        ),
        migrations.AddConstraint(
            model_name="generateddocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revision__isnull", True)),
                fields=(
                    "organization",
                    "workshop",
                    "template_version",
                    "output_kind",
                    "input_sha256",
                ),
                name="generated_document_idempotent_draft_output",
            ),
        ),
    ]
