# Generated by Django 5.2.17 on 2026-08-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0002_remove_generateddocument_generated_document_idempotent_output_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="generateddocument",
            name="renderer_version",
            field=models.CharField(default="weasyprint-69/v1", max_length=32),
        ),
        migrations.AlterField(
            model_name="generateddocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ausstehend"),
                    ("rendering", "Wird erzeugt"),
                    ("rendered", "Erzeugt"),
                    ("storing", "Wird extern gespeichert"),
                    ("stored", "Extern gespeichert"),
                    ("render_failed", "PDF-Erzeugung fehlgeschlagen"),
                    ("storage_failed", "Externe Speicherung fehlgeschlagen"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
    ]
