# Generated by Django 5.2.17 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("identities", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(default="de", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Hell"),
                    ("dark", "Dunkel"),
                    ("system", "Systemeinstellung"),
                ],
                default="system",
                max_length=16,
            ),
        ),
    ]
