# Generated by Django 5.2.17 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("identities", "0002_user_preferences")]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("organization_admin", "Organization Admin"),
                    ("editor", "Editor"),
                    ("workshop_user", "Workshop User"),
                ],
                max_length=32,
            ),
        )
    ]
