# Generated by Django 5.2.17 on 2026-08-28 17:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("workshops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Documentation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Entwurf"), ("finalized", "Abgeschlossen")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("conducted_as_planned", models.BooleanField(default=True)),
                ("report", models.TextField(blank=True, max_length=10000)),
                ("version", models.PositiveIntegerField(default=1)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_documentations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_documentations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentation",
                        to="workshops.workshop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentationRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("snapshot_schema_version", models.PositiveSmallIntegerField(default=1)),
                ("snapshot", models.JSONField()),
                ("snapshot_sha256", models.CharField(max_length=64)),
                ("optional_change_reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_documentation_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="documentation.documentation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="Facilitator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "documentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilitators",
                        to="documentation.documentation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facilitated_documentations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                (
                    "origin",
                    models.CharField(
                        choices=[("registered", "Angemeldet"), ("walk_in", "Spontan")],
                        max_length=16,
                    ),
                ),
                ("present", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "documentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="documentation.documentation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_entries",
                        to="workshops.workshopregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "display_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="documentation",
            constraint=models.UniqueConstraint(
                fields=("organization", "workshop"),
                name="documentation_unique_workshop_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentationrevision",
            constraint=models.UniqueConstraint(
                fields=("documentation", "number"), name="documentation_revision_unique_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="participantentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("registration__isnull", False)),
                fields=("documentation", "registration"),
                name="participant_unique_registration_per_documentation",
            ),
        ),
    ]
