# Generated by Django 5.2.17 on 2026-08-28 18:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentation", "0001_initial"),
        ("organizations", "0002_organization_address_organization_email_and_more"),
        ("workshops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Aktiv"), ("inactive", "Inaktiv")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_document_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_templates",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_document_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("project_title", models.CharField(blank=True, max_length=300)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("funding_text", models.TextField(blank=True, max_length=2000)),
                (
                    "attendance_text",
                    models.TextField(
                        default="Mit dem Eintrag auf dieser Liste bestätige ich die Teilnahme an oben aufgeführtem Workshop.",
                        max_length=2000,
                    ),
                ),
                ("configuration_schema_version", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_document_template_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="documentation.documenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for_templates",
                to="documentation.documenttemplateversion",
            ),
        ),
        migrations.CreateModel(
            name="TemplateAssetPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("organization", "Organisation"),
                            ("project_program", "Projekt / Programm"),
                            ("funder", "Förderer"),
                            ("client", "Auftraggeber"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("header", "Kopfbereich"),
                            ("project", "Projektbereich"),
                            ("funding_footer", "Förderbereich"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("show_funded_by_label", models.BooleanField(default=False)),
                ("accessible_name", models.CharField(blank=True, max_length=200)),
                (
                    "asset_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="organizations.brandassetversion",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_placements",
                        to="documentation.documenttemplateversion",
                    ),
                ),
            ],
            options={
                "ordering": ["zone", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TemplateCustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stable_key", models.UUIDField(default=uuid.uuid4)),
                ("label", models.CharField(max_length=200)),
                ("help_text", models.CharField(blank=True, max_length=500)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("short_text", "Kurzer Text"),
                            ("long_text", "Langer Text"),
                            ("integer", "Ganzzahl"),
                            ("decimal", "Dezimalzahl"),
                            ("boolean", "Ja / Nein"),
                            ("choice", "Auswahl"),
                            ("date", "Datum"),
                        ],
                        max_length=24,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("choice_options", models.JSONField(blank=True, default=list)),
                (
                    "presentation",
                    models.CharField(
                        choices=[
                            ("regular", "Normal"),
                            ("aggregate_statistic", "Aggregierte Statistik"),
                        ],
                        default="regular",
                        max_length=24,
                    ),
                ),
                ("include_in_output_kinds", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="documentation.documenttemplateversion",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TemplateOutputDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("final_report", "Abschlussdokument"),
                            ("attendance_sheet", "Teilnahmeliste"),
                            ("anonymized_report", "Anonymisierte Fassung"),
                        ],
                        max_length=32,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("include_participant_names", models.BooleanField(default=False)),
                ("include_signature_column", models.BooleanField(default=False)),
                ("include_statistics", models.BooleanField(default=True)),
                ("include_report", models.BooleanField(default=True)),
                ("include_facilitators", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="documentation.documenttemplateversion",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopTemplateAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documentation.documenttemplate",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documentation.documenttemplateversion",
                    ),
                ),
                (
                    "workshop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_assignment",
                        to="workshops.workshop",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="documentation",
            name="template_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentations",
                to="documentation.workshoptemplateassignment",
            ),
        ),
        migrations.CreateModel(
            name="DocumentationCustomFieldValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("field_stable_key", models.UUIDField()),
                ("value", models.JSONField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "documentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="documentation.documentation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_documentation_custom_fields",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("documentation", "field_stable_key"),
                        name="documentation_custom_value_unique_field",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="documenttemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "number"), name="document_template_version_unique_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="document_template_unique_name_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True), ("status", "active")),
                fields=("organization",),
                name="document_template_one_active_default_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatecustomfielddefinition",
            constraint=models.UniqueConstraint(
                fields=("template_version", "stable_key"),
                name="template_custom_field_unique_stable_key_per_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="templateoutputdefinition",
            constraint=models.UniqueConstraint(
                fields=("template_version", "kind"), name="template_output_unique_kind_per_version"
            ),
        ),
    ]
