# Generated by Django 5.2.17 on 2026-08-28 15:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Aktiv"), ("disabled", "Deaktiviert")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Berlin", max_length=64)),
                ("default_locale", models.CharField(default="de", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
