# Generated by Django 5.2.17 on 2026-08-28 18:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import werkblatt.organizations.models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="BrandAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                (
                    "default_role",
                    models.CharField(
                        choices=[
                            ("organization", "Organisation"),
                            ("project_program", "Projekt / Programm"),
                            ("funder", "Förderer"),
                            ("client", "Auftraggeber"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Aktiv"), ("inactive", "Inaktiv")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_brand_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_assets",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_brand_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="BrandAssetVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("original_filename", models.CharField(max_length=255)),
                ("media_type", models.CharField(max_length=32)),
                ("byte_size", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "original_file",
                    models.FileField(
                        max_length=500,
                        upload_to=werkblatt.organizations.models.brand_asset_original_path,
                    ),
                ),
                (
                    "preview_file",
                    models.FileField(
                        max_length=500,
                        upload_to=werkblatt.organizations.models.brand_asset_preview_path,
                    ),
                ),
                ("validation_profile_version", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="organizations.brandasset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_brand_asset_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.AddField(
            model_name="brandasset",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for_assets",
                to="organizations.brandassetversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="brandassetversion",
            constraint=models.UniqueConstraint(
                fields=("asset", "number"), name="brand_asset_version_unique_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="brandasset",
            constraint=models.UniqueConstraint(
                fields=("organization", "display_name"),
                name="brand_asset_unique_display_name_per_organization",
            ),
        ),
    ]
